---
- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
      - container-diff
  tags:
    - docker

- name: Enable and start docker
  service: name=docker.service enabled=yes state=started
  tags:
    - docker

- name: Add user to docker group
  user: name={{ user.name }} groups=docker append=yes
  tags:
    - user
    - docker

- name: Push Docker daemon config
  copy:
    src: docker/daemon.json
    dest: /etc/docker/
  notify:
    - restart docker
  tags:
    - docker
